### PR TITLE
Add resizer UI component

### PR DESCRIPTION
**Pull request by ZanzyTHEbar**
This pull request adds a new UI component called "Resizer". The Resizer component allows for resizing elements in the UI by dragging the edges. It includes functionality for both horizontal and vertical resizing. The Resizer component is dependent on the  "@solid-primitives/scheduled" packages.

### CODE REVIEW

**Review by ZanzyTHEbar — COMMENTED** [review]
TODO: Setup the example, and refine anything requested by repo owners/maintainers.

**Comment by carere** [comment]
@ZanzyTHEbar I really need this feature, I copied your code into my project `ui` folders, do you have some advices about using this component ?
Some code examples would be great, even pseudo code :)

**Comment by ZanzyTHEbar** [comment]
> @ZanzyTHEbar I really need this feature, I copied your code into my project `ui` folders, do you have some advices about using this component ? Some code examples would be great, even pseudo code :)

Sorry for getting back to you so late - yes here is a [gist](https://gist.github.com/ZanzyTHEbar/8f15aebf3accccc9e3301e69ead075b2).

**Comment by carere** [comment]
Thx for your answer but I ended using a modified version of [solid-resizable-panels](https://github.com/elite174/solid-resizable-panels) in order to resize severals panels on my app :)

**Comment by sek-consulting** [comment]
Thanks for the work you put in this component @ZanzyTHEbar :)
But for now I'm looking for something more in line to the resizable-panels component that shadcn/ui uses which might be solved by Corvu in a future update :)

But I want to keep this PR around and maybe make this a seperate component since it solves a different usecase :)

**Comment by sek-consulting** [comment]
I don't think I'll add this anytime soon.
Sorry but I'll close this for now. :)

**Pull request closed without merging**
