### PR TITLE
add: indeterminate state for checkbox

### PR DESCRIPTION
**Pull request by daelmaak**
Screenshot 2024-09-18 at 21 35 18

Closes https://github.com/sek-consulting/solid-ui/issues/128.

### CODE REVIEW

**Comment by daelmaak** [comment]
Not sure what's up with the deployment, can't see any details.

**Comment by sek-consulting** [comment]
It was just a little ".output folder is missing" error on vercel that happens sometime.
It's redeployed and can be proberly tested now.

**Comment by sek-consulting** [comment]
Just a quick question:

Could you switch from `Show` to `Switch` ? Seems more appropriate in this use case:
```tsx
import { Switch, Match } from "solid-js"

<Switch>
  <Match when={condition1}>
    <p>Outcome 1</p>
  </Match>
  <Match when={condition2}>
    <p>Outcome 2</p>
  </Match>
</Switch>
```tsx
https://docs.solidjs.com/concepts/control-flow/conditional-rendering

Also could you run `npm run build:registry` inside the apps/docs folder to create all the needed registry files.

Thanks :)

**Comment by daelmaak** [comment]
Done :).

**Comment by sek-consulting** [comment]
Awesome! Thanks :)

**Pull request merged**
